import { writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { buildPanel, REPEATS, type JudgeCase } from './judge/panel.ts'
import { askJudge, JUDGE_MODEL } from './judge/judge.ts'
import { buildJudgePrompt } from './judge/prompt.ts'
import { checkCitation, scorePanel, tally, type Judged } from './judge/score.ts'

/**
 * Puts every case in the panel to a model judge, `REPEATS` times each, and
 * writes one row per call.
 *
 *   npm run judge -- --out <file.tsv>   # the real thing; costs money
 *   npm run judge -- --prompt <case-id> # print what a judge is shown, call nothing
 *
 * The rows are the artifact. Every number this post prints about the judge is
 * recomputed from the committed file by `tools/judge/judgements.test.ts`, so
 * a tally that stops matching its own prose turns `npm test` red.
 */

export const HEADER = [
  'case',
  'kind',
  'known_answer',
  'repeat',
  'verdict',
  'agrees_with_known',
  'citation',
  'citation_check',
  'confidence',
  'input_tokens',
  'output_tokens',
  'reason',
].join('\t')

export function toRow(judgeCase: JudgeCase, judged: Judged): string {
  return [
    judged.case,
    judgeCase.known === undefined ? 'open' : 'control',
    judgeCase.known ?? '-',
    String(judged.repeat),
    judged.verdict,
    judgeCase.known === undefined
      ? '-'
      : judged.verdict === judgeCase.known
        ? 'yes'
        : 'no',
    judged.citation.replace(/\s+/g, ' ').trim() || '-',
    checkCitation(judgeCase, judged),
    judged.confidence.toFixed(2),
    String(judged.inputTokens),
    String(judged.outputTokens),
    judged.reason.replace(/\s+/g, ' ').trim(),
  ].join('\t')
}

/** Four at a time: the calls are independent, and ninety of them in series is an afternoon. */
const CONCURRENCY = 4

async function pooled<T>(
  jobs: readonly (() => Promise<T>)[],
  limit: number,
): Promise<T[]> {
  const out: T[] = new Array(jobs.length)
  let next = 0

  async function worker(): Promise<void> {
    for (;;) {
      const index = next
      next += 1
      const job = jobs[index]
      if (job === undefined) return
      out[index] = await job()
    }
  }

  await Promise.all(
    Array.from({ length: Math.min(limit, jobs.length) }, () => worker()),
  )
  return out
}

async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const panel = buildPanel()

  const promptIndex = args.indexOf('--prompt')
  if (promptIndex !== -1) {
    const id = args[promptIndex + 1]
    const found = panel.find((item) => item.id === id)
    if (found === undefined) {
      console.error(
        `no case "${id}". cases: ${panel.map((item) => item.id).join(', ')}`,
      )
      process.exit(1)
    }
    console.log(buildJudgePrompt(found.trace, found.question))
    return
  }

  const outIndex = args.indexOf('--out')
  const out = args[outIndex + 1]
  if (outIndex === -1 || out === undefined) {
    console.error('usage: npm run judge -- --out <file.tsv>')
    process.exit(1)
  }

  const jobs = panel.flatMap((judgeCase) =>
    Array.from({ length: REPEATS }, (_unused, repeat) => async () => {
      const call = await askJudge(judgeCase)
      const judged: Judged = {
        case: judgeCase.id,
        repeat: repeat + 1,
        verdict: call.judgement.verdict,
        citation: call.judgement.citation,
        confidence: call.judgement.confidence,
        reason: call.judgement.reason,
        inputTokens: call.inputTokens,
        outputTokens: call.outputTokens,
      }
      console.error(
        `${judged.case} #${judged.repeat}: ${judged.verdict} (${judged.confidence})`,
      )
      return { judgeCase, judged }
    }),
  )

  const results = await pooled(jobs, CONCURRENCY)
  const judgements = results.map((result) => result.judged)
  const score = scorePanel(panel, judgements)

  const provenance = [
    `# generated by: npm run judge -- --out ${out}`,
    `# judge model: ${JUDGE_MODEL}`,
    `# repeats per case: ${REPEATS}`,
    `# judge calls: ${judgements.length}`,
    `# ran: ${new Date().toISOString()}`,
    `# input tokens: ${score.inputTokens}`,
    `# output tokens: ${score.outputTokens}`,
  ]

  writeFileSync(
    out,
    [
      ...provenance,
      HEADER,
      ...results.map((result) => toRow(result.judgeCase, result.judged)),
      '',
    ].join('\n'),
    'utf8',
  )

  for (const control of score.controls) {
    console.error(
      `control ${control.case}: ${control.correct}/${control.runs} agree with ${control.known}` +
        ` (majority ${control.majority}), ${control.badCitations} bad citation(s)`,
    )
  }
  for (const open of score.open) {
    const counts = tally(open.case, judgements).counts
    console.error(
      `open ${open.case}: ${JSON.stringify(counts)} — decided ${open.decided}/${open.runs}` +
        ` at mean confidence ${open.confidenceWhenDecided.toFixed(2)}`,
    )
  }
  console.error(
    `\n${score.correct}/${score.calls} control calls correct; ` +
      `${score.majoritiesCorrect}/${score.controlCount} control majorities correct; ` +
      `${score.unstableControls}/${score.controlCount} controls unstable`,
  )
  console.error(`wrote ${out}`)
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main().catch((error: unknown) => {
    console.error(error)
    process.exit(1)
  })
}
